services:
  postgres:
    image: postgres:15.2-alpine
    hostname: postgres
    ports:
      - 15432:5432
    restart: always
    environment:
      POSTGRES_DB: testDb
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPassword